package com.jinloes.prpilot.model

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmOverloads

@Serializable
data class PullRequest @JvmOverloads constructor(
    val title: String,
    val htmlUrl: String,
    val owner: String,
    val repo: String,
    val number: Int,
    val body: String,
    val author: String,
    val createdAt: String,
    val isDraft: Boolean = false,
) {
    // Java interop: getter methods are generated by Kotlin for data class properties.
    // toString mirrors @ToString(of = {"owner", "repo", "number", "title"}).
    override fun toString(): String = "PullRequest(owner=$owner, repo=$repo, number=$number, title=$title)"
}
